/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.admin;

import excepciones.UsuarioBloqueadoException;
import excepciones.UsuarioNoBloqueadoException;
import java.awt.Color;
import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import modelo.instituto.Instituto;
import modelo.usuarios.Admin;
import modelo.usuarios.Alumno;
/**
 *
 * @author user
 */
public class gestionAlumnos extends javax.swing.JFrame {

    Admin admin;
    Instituto instituto;
    DefaultTableModel modeloTabla;
    
    public gestionAlumnos(Admin admin, Instituto instituto) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.admin = admin;
        this.instituto = instituto;
        modeloTabla = (DefaultTableModel) tableListadoAlumnos.getModel();
        cargarTabla(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblRegresar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListadoAlumnos = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        lblResetLista = new javax.swing.JLabel();
        btnBloquear = new javax.swing.JButton();
        btnResetPass = new javax.swing.JButton();
        btnDesbloquear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel9.setBackground(new java.awt.Color(0, 51, 102));

        jPanel10.setBackground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 9, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        lblTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 16)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblTitulo.setText("Gestión de Alumnos");

        lblRegresar.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblRegresar.setForeground(new java.awt.Color(240, 240, 240));
        lblRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/volverAtras2.png"))); // NOI18N
        lblRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegresarMouseClicked(evt);
            }
        });

        tableListadoAlumnos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 102), 1, true));
        tableListadoAlumnos.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        tableListadoAlumnos.setForeground(new java.awt.Color(0, 51, 102));
        tableListadoAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Nombre", "Apellido", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableListadoAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableListadoAlumnos.setGridColor(new java.awt.Color(255, 255, 255));
        tableListadoAlumnos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tableListadoAlumnos.getTableHeader().setResizingAllowed(false);
        tableListadoAlumnos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tableListadoAlumnos);

        jPanel3.setBackground(new java.awt.Color(0, 67, 135));

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nombre");

        txtNombre.setBackground(new java.awt.Color(0, 67, 135));
        txtNombre.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(240, 240, 240));
        txtNombre.setBorder(null);
        txtNombre.setCaretColor(new java.awt.Color(240, 240, 240));
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Apellido");

        txtApellido.setBackground(new java.awt.Color(0, 67, 135));
        txtApellido.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(240, 240, 240));
        txtApellido.setBorder(null);
        txtApellido.setCaretColor(new java.awt.Color(240, 240, 240));
        txtApellido.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel9.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");

        txtDni.setBackground(new java.awt.Color(0, 67, 135));
        txtDni.setFont(new java.awt.Font("Lucida Sans", 0, 11)); // NOI18N
        txtDni.setForeground(new java.awt.Color(240, 240, 240));
        txtDni.setBorder(null);
        txtDni.setCaretColor(new java.awt.Color(240, 240, 240));
        txtDni.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/buscarUsuario2.png"))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(0, 51, 102));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("BUSCAR");
        btnBuscar.setBorder(null);
        btnBuscar.setContentAreaFilled(false);
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setFocusable(false);
        btnBuscar.setOpaque(true);
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBuscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBuscarMouseExited(evt);
            }
        });
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel2)
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApellido)
                                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                                .addComponent(jLabel9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDni)
                                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombre)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)))))
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(35, 35, 35)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel7.setBackground(new java.awt.Color(0, 67, 135));

        lblResetLista.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblResetLista.setForeground(new java.awt.Color(255, 255, 255));
        lblResetLista.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblResetLista.setText("Actualizar listado");
        lblResetLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblResetLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetListaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblResetListaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblResetListaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblResetLista)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblResetLista, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnBloquear.setBackground(new java.awt.Color(0, 67, 135));
        btnBloquear.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnBloquear.setForeground(new java.awt.Color(255, 255, 255));
        btnBloquear.setText("BLOQUEAR");
        btnBloquear.setBorder(null);
        btnBloquear.setContentAreaFilled(false);
        btnBloquear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnBloquear.setFocusable(false);
        btnBloquear.setOpaque(true);
        btnBloquear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBloquearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBloquearMouseExited(evt);
            }
        });
        btnBloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloquearActionPerformed(evt);
            }
        });

        btnResetPass.setBackground(new java.awt.Color(0, 67, 135));
        btnResetPass.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnResetPass.setForeground(new java.awt.Color(255, 255, 255));
        btnResetPass.setText("RESET CONTRASEÑA");
        btnResetPass.setBorder(null);
        btnResetPass.setContentAreaFilled(false);
        btnResetPass.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnResetPass.setFocusable(false);
        btnResetPass.setOpaque(true);
        btnResetPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnResetPassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnResetPassMouseExited(evt);
            }
        });
        btnResetPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPassActionPerformed(evt);
            }
        });

        btnDesbloquear.setBackground(new java.awt.Color(0, 67, 135));
        btnDesbloquear.setFont(new java.awt.Font("Segoe UI Historic", 1, 12)); // NOI18N
        btnDesbloquear.setForeground(new java.awt.Color(255, 255, 255));
        btnDesbloquear.setText("DESBLOQUEAR");
        btnDesbloquear.setBorder(null);
        btnDesbloquear.setContentAreaFilled(false);
        btnDesbloquear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnDesbloquear.setFocusable(false);
        btnDesbloquear.setOpaque(true);
        btnDesbloquear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDesbloquearMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDesbloquearMouseExited(evt);
            }
        });
        btnDesbloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesbloquearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(btnBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesbloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRegresar)
                        .addGap(282, 282, 282)
                        .addComponent(lblTitulo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRegresar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnDesbloquear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnBloquear, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnResetPass, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegresarMouseClicked
         dispose();
        visualAdmin vA = new visualAdmin(this.admin, this.instituto);
        vA.jTabbedPane.setSelectedIndex(0);
        vA.setVisible(true);
    }//GEN-LAST:event_lblRegresarMouseClicked

    private void btnBuscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseEntered
        btnBuscar.setBackground(new Color(0,56,110));
    }//GEN-LAST:event_btnBuscarMouseEntered

    private void btnBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseExited
        btnBuscar.setBackground(new Color(0,51,102));
    }//GEN-LAST:event_btnBuscarMouseExited

    private void lblResetListaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetListaMouseEntered
        setUnderline(lblResetLista, true);
    }//GEN-LAST:event_lblResetListaMouseEntered

    private void lblResetListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetListaMouseExited
        setUnderline(lblResetLista, false);
    }//GEN-LAST:event_lblResetListaMouseExited

    private void btnBloquearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloquearMouseEntered
        btnBloquear.setBackground(new Color(0,56,110));
    }//GEN-LAST:event_btnBloquearMouseEntered

    private void btnBloquearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBloquearMouseExited
        btnBloquear.setBackground(new Color(0,67,135));
    }//GEN-LAST:event_btnBloquearMouseExited

    //cambioss
    private void btnBloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloquearActionPerformed
        int filaSeleccionada = obtenerFilaSeleccionada();
        String dniSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        ArrayList<Alumno> listaAlumnos = instituto.getAlumnos();
        
        JDialogDeseaContinuar dialog2 = new JDialogDeseaContinuar(this, true);
        dialog2.setVisible(true);
        int seleccion = dialog2.getReturnStatus();
        
        
        //Aplicar sancion
        if(seleccion == 1){
            for (Alumno alumno : listaAlumnos) {
                if (alumno.getDni().equals(dniSeleccionado)) {
                    try
                    {
                        JDialogMotivoSancion dialog = new JDialogMotivoSancion(this,true);
                        dialog.setVisible(true);
                        String motivo = dialog.obtenerTextoIngresado();
                        if(motivo.length()>3 && !motivo.isEmpty() && motivo.matches("[a-zA-Z0-9\\s]+"))
                        {
                            admin.bloquearUsuario(alumno, motivo);
                            new JDialogInfo(this, true, "El usuario se bloqueó correctamente").setVisible(true);
                            serializarInstituto();
                        }
                        else new JDialogError(this,true,"Motivo inválido. \n  Debe contener solo letras y números, y tener al menos 3 caracteres.").setVisible(true);
                    }
                    catch (UsuarioBloqueadoException e)
                    {
                        new JDialogError(this,true,e).setVisible(true);
                    }
                }
            }
        }
        modeloTabla.setRowCount(0);
        cargarTabla(modeloTabla);
        
    }//GEN-LAST:event_btnBloquearActionPerformed

    private void btnResetPassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPassMouseEntered
        btnResetPass.setBackground(new Color(0,56,110));
    }//GEN-LAST:event_btnResetPassMouseEntered

    private void btnResetPassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnResetPassMouseExited
        btnResetPass.setBackground(new Color(0,67,135));
    }//GEN-LAST:event_btnResetPassMouseExited

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        modeloTabla.setRowCount(0);
    
        String nombre = txtNombre.getText().toLowerCase();
        String apellido = txtApellido.getText().toLowerCase();
        String dni = txtDni.getText();

        ArrayList<Alumno> alumnos = instituto.getAlumnos();

        for(Alumno alumno : alumnos)
        {
            if(alumno.getDni().equals(dni) || alumno.getNombre().equals(nombre) || alumno.getApellido().equals(apellido) ||
              (alumno.getNombre().contains(nombre) && alumno.getApellido().contains(apellido) && alumno.getDni().contains(dni)))
            {
                String estado = "habilitado";
                if(alumno.getSancion() != null)
                {
                    estado = "<< inhabilitado >>";
                }
                Object[] fila = {alumno.getDni(), alumno.getNombre(), alumno.getApellido(), estado};
                modeloTabla.addRow(fila);
            }
        }
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtDni.setText("");
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void lblResetListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetListaMouseClicked
        modeloTabla.setRowCount(0);
        cargarTabla(modeloTabla);
    }//GEN-LAST:event_lblResetListaMouseClicked

    private void btnResetPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPassActionPerformed
        
        int filaSeleccionada = obtenerFilaSeleccionada();
        String dniSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        Alumno alumno = buscarAlumnoPorDNI(dniSeleccionado);
        
        JDialogDeseaContinuar dialog = new JDialogDeseaContinuar(this, true);
        dialog.setVisible(true);
        int seleccion = dialog.getReturnStatus();
        
        if (seleccion == 1) {
            admin.blanquearContraseña(alumno);
            serializarInstituto();
        }
        
    }//GEN-LAST:event_btnResetPassActionPerformed

    private void btnDesbloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesbloquearActionPerformed
        int filaSeleccionada = tableListadoAlumnos.getSelectedRow();
        String dniSeleccionado = modeloTabla.getValueAt(filaSeleccionada, 0).toString();
        
        ArrayList<Alumno> alumnosBloqueados = obtenerAlumnosBloqueados();
        
        if(alumnosBloqueados.size()>0){
            for(Alumno alumno : alumnosBloqueados)
            {
                if(alumno.getDni().equals(dniSeleccionado))
                {
                    //mostramos dialogo para ver si desea continuar con la accion de desbloqueo
                    JDialogDeseaContinuar dialog = new JDialogDeseaContinuar(this, true);
                    dialog.setVisible(true);
                    int seleccion = dialog.getReturnStatus();
                    if(seleccion == 1)
                    {
                        try
                        {
                            admin.desbloquearUsuario(alumno);
                            serializarInstituto();
                            break;
                        }
                        catch(UsuarioNoBloqueadoException e)
                        {
                            new JDialogError(this,true,e).setVisible(true);
                        }
                    }
                }
            }
        }
        modeloTabla.setRowCount(0);
        cargarTabla(modeloTabla);
        
    }//GEN-LAST:event_btnDesbloquearActionPerformed

    private void btnDesbloquearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearMouseEntered
        btnDesbloquear.setBackground(new Color(0,56,110));
    }//GEN-LAST:event_btnDesbloquearMouseEntered

    private void btnDesbloquearMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesbloquearMouseExited
        btnDesbloquear.setBackground(new Color(0,67,135));
    }//GEN-LAST:event_btnDesbloquearMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBloquear;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnDesbloquear;
    private javax.swing.JButton btnResetPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblRegresar;
    private javax.swing.JLabel lblResetLista;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tableListadoAlumnos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables

  private static void setUnderline(JLabel label, boolean underline) {
        Font font = label.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, underline ? TextAttribute.UNDERLINE_ON : null);
        label.setFont(font.deriveFont(attributes));
    }
    
    public void cargarTabla(DefaultTableModel modeloTabla)
    {
        ArrayList<Alumno> listaAlumnos = instituto.getAlumnos();
        
        // Agregar filas al modelo de tabla a partir de los datos de los docentes
        for (Alumno alumno : listaAlumnos) {
            
            String estado = "habilitado";
            if(alumno.getSancion() != null)
            {
                estado = "<< inhabilitado >>";
            }
            Object[] fila = {alumno.getDni(), alumno.getNombre(), alumno.getApellido(), estado};
            modeloTabla.addRow(fila);
        }
        
    }
    
    private ArrayList<Alumno> obtenerAlumnosBloqueados()
    {
        ArrayList<Alumno> alumnos = instituto.getAlumnos();
        ArrayList<Alumno> alumnosBloqueados = new ArrayList();

        for (Alumno alumno : alumnos) {
            if(alumno.getSancion() != null)
            {
                alumnosBloqueados.add(alumno);
            }
        }
            return alumnosBloqueados;
        
    }
    
    
    private int obtenerFilaSeleccionada() {
        return tableListadoAlumnos.getSelectedRow();
    }
    
  
    private Alumno buscarAlumnoPorDNI(String dni) 
    {
        ArrayList<Alumno> listaAlumnos = instituto.getAlumnos();

        for (Alumno alumno : listaAlumnos) {
            if (alumno.getDni().equals(dni)) {
                return alumno; // Se encontró al docente, devuelve el objeto Docente
            }
        }

        return null; // No se encontró al docente con el DNI especificado
    }
    
    
    
    public void serializarAdmin()
    {
        try 
        {
            FileOutputStream archivoSalida = new FileOutputStream("admin_serializado.dat");
            ObjectOutputStream objetoSalida = new ObjectOutputStream(archivoSalida);
            objetoSalida.writeObject(this.admin);
            objetoSalida.close();
            archivoSalida.close();
        }
        catch (IOException e){ 
            e.printStackTrace();
        }
    }
     
    public void serializarInstituto()
    {
        try {
            FileOutputStream archivoSalida = new FileOutputStream("instituto_serializados.dat");
            ObjectOutputStream objetoSalida = new ObjectOutputStream(archivoSalida);
            objetoSalida.writeObject(instituto);
            objetoSalida.close();
            archivoSalida.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
}
