/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.admin;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import modelo.instituto.Instituto;
import modelo.usuarios.Admin;
import visual.inicio.Inicio;
import visual.inicio.cambiarContrasenhaUser;

/**
 *
 * @author user
 */
public class visualAdmin extends javax.swing.JFrame {

    
    Admin admin;
    Instituto instituto;
    
    
    public visualAdmin(Admin admin, Instituto instituto) {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.admin = admin;
        this.instituto = instituto;
        
        lblBienvenido.setText("Bienvenido Administrador.");
        
        serializarInstituto();
        serializarAdmin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblBienvenido = new javax.swing.JLabel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblAgregarUsuario = new javax.swing.JLabel();
        lblAgregarUsuario2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        lblGestionAlumnos = new javax.swing.JLabel();
        lblGestionAlumnos2 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lblGestionDocente = new javax.swing.JLabel();
        lblGestionDocente2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblGestionCurso = new javax.swing.JLabel();
        lblGestionCurso2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblSolicitudHabilitacion = new javax.swing.JLabel();
        lblSolicitudHabilitacion2 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lblCursosFinalizados = new javax.swing.JLabel();
        lblCursosFinalizados2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblCursosActivos = new javax.swing.JLabel();
        lblCursosActivos2 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        lblCursosCancelados = new javax.swing.JLabel();
        lblCursosCancelados2 = new javax.swing.JLabel();
        lblCambiarContrasenha = new javax.swing.JLabel();
        lblCerrarSesion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 102));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        lblBienvenido.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(240, 240, 240));
        lblBienvenido.setText("Nombre Usuario");

        jTabbedPane.setBackground(new java.awt.Color(0, 60, 120));
        jTabbedPane.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N

        lblAgregarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/agregarUsuario.png"))); // NOI18N
        lblAgregarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAgregarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarUsuarioMouseClicked(evt);
            }
        });

        lblAgregarUsuario2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblAgregarUsuario2.setForeground(new java.awt.Color(0, 51, 102));
        lblAgregarUsuario2.setText("Agregar usuario");
        lblAgregarUsuario2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblAgregarUsuario2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarUsuario2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgregarUsuario2))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblAgregarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(lblAgregarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAgregarUsuario2))
        );

        lblGestionAlumnos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblGestionAlumnos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGestionAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionAlumnosMouseClicked(evt);
            }
        });

        lblGestionAlumnos2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblGestionAlumnos2.setForeground(new java.awt.Color(0, 51, 102));
        lblGestionAlumnos2.setText("Gestión alumnos");
        lblGestionAlumnos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblGestionAlumnos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionAlumnos2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionAlumnos)
                .addGap(30, 30, 30))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGestionAlumnos2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(lblGestionAlumnos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionAlumnos2))
        );

        lblGestionDocente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblGestionDocente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionDocenteMouseClicked(evt);
            }
        });

        lblGestionDocente2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblGestionDocente2.setForeground(new java.awt.Color(0, 51, 102));
        lblGestionDocente2.setText("Gestión docentes");
        lblGestionDocente2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionDocente2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionDocente2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(lblGestionDocente2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                        .addComponent(lblGestionDocente)
                        .addGap(20, 20, 20))))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(lblGestionDocente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionDocente2))
        );

        lblGestionCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblGestionCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionCursoMouseClicked(evt);
            }
        });

        lblGestionCurso2.setFont(new java.awt.Font("Lucida Sans", 0, 12)); // NOI18N
        lblGestionCurso2.setForeground(new java.awt.Color(0, 51, 102));
        lblGestionCurso2.setText("Gestión cursos");
        lblGestionCurso2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGestionCurso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGestionCurso2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblGestionCurso)
            .addComponent(lblGestionCurso2)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lblGestionCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblGestionCurso2))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Gestión de usuarios", jPanel2);

        lblSolicitudHabilitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblSolicitudHabilitacion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSolicitudHabilitacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitudHabilitacionMouseClicked(evt);
            }
        });

        lblSolicitudHabilitacion2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblSolicitudHabilitacion2.setForeground(new java.awt.Color(0, 51, 102));
        lblSolicitudHabilitacion2.setText("Solicitudes de Habilitación");
        lblSolicitudHabilitacion2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblSolicitudHabilitacion2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSolicitudHabilitacion2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblSolicitudHabilitacion))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblSolicitudHabilitacion2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lblSolicitudHabilitacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSolicitudHabilitacion2))
        );

        lblCursosFinalizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosFinalizados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosFinalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosFinalizadosMouseClicked(evt);
            }
        });

        lblCursosFinalizados2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosFinalizados2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosFinalizados2.setText("Cursos finalizados");
        lblCursosFinalizados2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosFinalizados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosFinalizados2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursosFinalizados2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                        .addComponent(lblCursosFinalizados)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addComponent(lblCursosFinalizados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosFinalizados2))
        );

        lblCursosActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosActivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosActivosMouseClicked(evt);
            }
        });

        lblCursosActivos2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosActivos2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosActivos2.setText("Cursos activos");
        lblCursosActivos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosActivos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosActivos2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursosActivos)
                    .addComponent(lblCursosActivos2))
                .addGap(10, 10, 10))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lblCursosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosActivos2))
        );

        lblCursosCancelados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosCancelados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosCancelados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosCanceladosMouseClicked(evt);
            }
        });

        lblCursosCancelados2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosCancelados2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosCancelados2.setText("Cursos cancelados");
        lblCursosCancelados2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosCancelados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosCancelados2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursosCancelados2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addComponent(lblCursosCancelados)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(lblCursosCancelados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosCancelados2))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67))
        );

        jTabbedPane.addTab("Gestión de cursos", jPanel3);

        lblCambiarContrasenha.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCambiarContrasenha.setForeground(new java.awt.Color(240, 240, 240));
        lblCambiarContrasenha.setText("Cambiar contraseña");
        lblCambiarContrasenha.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCambiarContrasenha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarContrasenhaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCambiarContrasenhaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCambiarContrasenhaMouseExited(evt);
            }
        });

        lblCerrarSesion1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCerrarSesion1.setForeground(new java.awt.Color(240, 240, 240));
        lblCerrarSesion1.setText("Cerrar sesión");
        lblCerrarSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCerrarSesion1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesion1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesion1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesion1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblBienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCambiarContrasenha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCerrarSesion1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCambiarContrasenha)
                    .addComponent(lblCerrarSesion1))
                .addGap(16, 16, 16))
        );

        jTabbedPane.getAccessibleContext().setAccessibleName("Gestión de usuarios");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCursosCancelados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosCancelados2MouseClicked
        this.setVisible(false);
        new cursosCancelados(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosCancelados2MouseClicked

    private void lblCursosCanceladosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosCanceladosMouseClicked
        this.setVisible(false);
        new cursosCancelados(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosCanceladosMouseClicked

    private void lblCursosActivos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosActivos2MouseClicked
        this.setVisible(false);
        new cursosActivos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosActivos2MouseClicked

    private void lblCursosActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosActivosMouseClicked
        this.setVisible(false);
        new cursosActivos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosActivosMouseClicked

    private void lblCursosFinalizados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosFinalizados2MouseClicked
        this.setVisible(false);
        new cursosFinalizados(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosFinalizados2MouseClicked

    private void lblCursosFinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosFinalizadosMouseClicked
        this.setVisible(false);
        new cursosFinalizados(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosFinalizadosMouseClicked

    private void lblSolicitudHabilitacion2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudHabilitacion2MouseClicked
        this.setVisible(false);
        new solicitudesHabilitacion(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblSolicitudHabilitacion2MouseClicked

    private void lblSolicitudHabilitacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSolicitudHabilitacionMouseClicked
        this.setVisible(false);
        new solicitudesHabilitacion(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblSolicitudHabilitacionMouseClicked

    private void lblGestionDocente2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionDocente2MouseClicked
        this.setVisible(false);
        new gestionDocente(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionDocente2MouseClicked

    private void lblGestionDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionDocenteMouseClicked
        this.setVisible(false);
        new gestionDocente(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionDocenteMouseClicked

    private void lblAgregarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarUsuarioMouseClicked
        this.setVisible(false);
        new agregarUsuario(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblAgregarUsuarioMouseClicked

    private void lblGestionAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionAlumnosMouseClicked
        this.setVisible(false);
        new gestionAlumnos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionAlumnosMouseClicked

    private void lblGestionAlumnos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionAlumnos2MouseClicked
        this.setVisible(false);
        new gestionAlumnos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionAlumnos2MouseClicked

    private void lblAgregarUsuario2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarUsuario2MouseClicked
        this.setVisible(false);
        new agregarUsuario(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblAgregarUsuario2MouseClicked

    private void lblCambiarContrasenhaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContrasenhaMouseEntered
        setUnderline(lblCambiarContrasenha, true);
    }//GEN-LAST:event_lblCambiarContrasenhaMouseEntered

    private void lblCambiarContrasenhaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContrasenhaMouseExited
        setUnderline(lblCambiarContrasenha, false);
    }//GEN-LAST:event_lblCambiarContrasenhaMouseExited

    private void lblCambiarContrasenhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContrasenhaMouseClicked
        
        new cambiarContrasenhaUser(admin,instituto).setVisible(true);
    }//GEN-LAST:event_lblCambiarContrasenhaMouseClicked

    private void lblCerrarSesion1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesion1MouseClicked

        dispose();
        new Inicio(this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCerrarSesion1MouseClicked

    private void lblCerrarSesion1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesion1MouseEntered
        setUnderline(lblCerrarSesion1, false);
    }//GEN-LAST:event_lblCerrarSesion1MouseEntered

    private void lblCerrarSesion1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesion1MouseExited
        setUnderline(lblCerrarSesion1, true);
    }//GEN-LAST:event_lblCerrarSesion1MouseExited

    private void lblGestionCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionCursoMouseClicked
        this.setVisible(false);
        new gestionCursos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionCursoMouseClicked

    private void lblGestionCurso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGestionCurso2MouseClicked
        this.setVisible(false);
        new gestionCursos(this.admin, this.instituto).setVisible(true);
    }//GEN-LAST:event_lblGestionCurso2MouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JLabel lblAgregarUsuario;
    private javax.swing.JLabel lblAgregarUsuario2;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCambiarContrasenha;
    private javax.swing.JLabel lblCerrarSesion1;
    private javax.swing.JLabel lblCursosActivos;
    private javax.swing.JLabel lblCursosActivos2;
    private javax.swing.JLabel lblCursosCancelados;
    private javax.swing.JLabel lblCursosCancelados2;
    private javax.swing.JLabel lblCursosFinalizados;
    private javax.swing.JLabel lblCursosFinalizados2;
    private javax.swing.JLabel lblGestionAlumnos;
    private javax.swing.JLabel lblGestionAlumnos2;
    private javax.swing.JLabel lblGestionCurso;
    private javax.swing.JLabel lblGestionCurso2;
    private javax.swing.JLabel lblGestionDocente;
    private javax.swing.JLabel lblGestionDocente2;
    private javax.swing.JLabel lblSolicitudHabilitacion;
    private javax.swing.JLabel lblSolicitudHabilitacion2;
    // End of variables declaration//GEN-END:variables

    private static void setUnderline(JLabel label, boolean underline) {
        Font font = label.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, underline ? TextAttribute.UNDERLINE_ON : null);
        label.setFont(font.deriveFont(attributes));
    }    
    
    public void serializarAdmin() {
    if (this.admin == null) {
        System.err.println("El objeto admin es null. No se puede serializar.");
        return;
    }

    FileOutputStream archivoSalida = null;
    ObjectOutputStream objetoSalida = null;

    try {
        archivoSalida = new FileOutputStream("admin_serializado.dat");
        objetoSalida = new ObjectOutputStream(archivoSalida);
        objetoSalida.writeObject(admin);
    } catch (IOException e) {
        e.printStackTrace();
    } finally {
        try {
            if (objetoSalida != null) {
                objetoSalida.close();
            }
            if (archivoSalida != null) {
                archivoSalida.close();
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
     
    public void serializarInstituto()
    {
        try {
            FileOutputStream archivoSalida = new FileOutputStream("instituto_serializados.dat");
            ObjectOutputStream objetoSalida = new ObjectOutputStream(archivoSalida);
            objetoSalida.writeObject(instituto);
            objetoSalida.close();
            archivoSalida.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }
    
}
