/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual.docente;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JLabel;
import modelo.cursos.Curso;
import modelo.instituto.Instituto;
import modelo.usuarios.Docente;
import visual.admin.cambiarContrasenhaFirst;
import visual.inicio.Inicio;
import visual.inicio.cambiarContrasenhaUser;

/**
 *
 * @author user
 */
public class visualDocente extends javax.swing.JFrame {

    
    Docente userDocente;
    Instituto instituto;
   
    public visualDocente(Docente docente, Instituto instituto) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userDocente = docente;
        this.instituto = instituto;
        
        lblTitulo.setText("Bienvenido,  " + userDocente.getNombre());
        setLabelCursosCerrados();
        setLabelCursosFinalizados();
        setLabelSanciones();
        serializarInstituto();
    }
    
    public visualDocente(Docente docente) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.userDocente = docente;
        this.instituto = instituto;
        
        setLabelCursosCerrados();
        setLabelCursosFinalizados();
        setLabelSanciones();
        serializarInstituto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        lblCursosFinalizados = new javax.swing.JLabel();
        lblCursosFinalizados2 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        lblCursosPropuestos = new javax.swing.JLabel();
        lblCursosPropuestos2 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lblCursosActivos = new javax.swing.JLabel();
        lblCursosActivos2 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        lblProponerCurso = new javax.swing.JLabel();
        lblProponerCurso2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblCantidadCursosCerrado = new javax.swing.JLabel();
        lblCantidadCursosFinalizados = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblCambiarContraseña = new javax.swing.JLabel();
        lblCerrarSesion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        lblTitulo.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(240, 240, 240));
        lblTitulo.setText("Nombre Usuario");

        jTabbedPane1.setBackground(new java.awt.Color(0, 51, 102));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        lblCursosFinalizados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosFinalizados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosFinalizados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosFinalizadosMouseClicked(evt);
            }
        });

        lblCursosFinalizados2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosFinalizados2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosFinalizados2.setText("Cursos finalizados");
        lblCursosFinalizados2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosFinalizados2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosFinalizados2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCursosFinalizados2))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblCursosFinalizados)))
                .addContainerGap())
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addComponent(lblCursosFinalizados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosFinalizados2))
        );

        lblCursosPropuestos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosPropuestos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosPropuestos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosPropuestosMouseClicked(evt);
            }
        });

        lblCursosPropuestos2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosPropuestos2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosPropuestos2.setText("Cursos propuestos");
        lblCursosPropuestos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosPropuestos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosPropuestos2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursosPropuestos2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel18Layout.createSequentialGroup()
                        .addComponent(lblCursosPropuestos)
                        .addGap(17, 17, 17)))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addComponent(lblCursosPropuestos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosPropuestos2))
        );

        lblCursosActivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblCursosActivos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosActivosMouseClicked(evt);
            }
        });

        lblCursosActivos2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblCursosActivos2.setForeground(new java.awt.Color(0, 51, 102));
        lblCursosActivos2.setText("Cursos activos");
        lblCursosActivos2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCursosActivos2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCursosActivos2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCursosActivos)
                    .addComponent(lblCursosActivos2))
                .addGap(10, 10, 10))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(lblCursosActivos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCursosActivos2))
        );

        lblProponerCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagenes/listaUsuarios1.png"))); // NOI18N
        lblProponerCurso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblProponerCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProponerCursoMouseClicked(evt);
            }
        });

        lblProponerCurso2.setFont(new java.awt.Font("Segoe UI Historic", 0, 14)); // NOI18N
        lblProponerCurso2.setForeground(new java.awt.Color(0, 51, 102));
        lblProponerCurso2.setText("Proponer curso");
        lblProponerCurso2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblProponerCurso2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProponerCurso2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(lblProponerCurso)
                .addGap(24, 24, 24))
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblProponerCurso2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lblProponerCurso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblProponerCurso2))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jTabbedPane1.addTab("Mis cursos", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalles", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 102));
        jLabel7.setText("Cursos activos:");

        jLabel8.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 102));
        jLabel8.setText("Cursos finalizados:");

        lblCantidadCursosCerrado.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCantidadCursosCerrado.setForeground(new java.awt.Color(0, 51, 102));

        lblCantidadCursosFinalizados.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCantidadCursosFinalizados.setForeground(new java.awt.Color(0, 51, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadCursosCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCantidadCursosFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lblCantidadCursosCerrado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(lblCantidadCursosFinalizados, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuración", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Historic", 1, 16), new java.awt.Color(0, 51, 102))); // NOI18N

        lblCambiarContraseña.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCambiarContraseña.setForeground(new java.awt.Color(0, 51, 102));
        lblCambiarContraseña.setText("Cambiar contraseña");
        lblCambiarContraseña.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCambiarContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCambiarContraseñaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCambiarContraseñaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCambiarContraseñaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCambiarContraseña)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblCambiarContraseña)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mi cuenta", jPanel2);

        lblCerrarSesion.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        lblCerrarSesion.setForeground(new java.awt.Color(240, 240, 240));
        lblCerrarSesion.setText("Cerrar sesión");
        lblCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lblCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCerrarSesionMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCerrarSesion)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCerrarSesion)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCursosActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosActivosMouseClicked
        this.dispose();
        new cursosActivos(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosActivosMouseClicked

    private void lblCursosActivos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosActivos2MouseClicked
        this.dispose();
        new cursosActivos(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosActivos2MouseClicked

    private void lblProponerCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProponerCursoMouseClicked
        this.dispose();
        new proponerCurso(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblProponerCursoMouseClicked

    private void lblProponerCurso2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProponerCurso2MouseClicked
        this.dispose();
        new proponerCurso(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblProponerCurso2MouseClicked

    private void lblCursosFinalizadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosFinalizadosMouseClicked
        this.dispose();
        new cursosFinalizados(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosFinalizadosMouseClicked

    private void lblCursosFinalizados2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosFinalizados2MouseClicked
        this.dispose();
        new cursosFinalizados(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosFinalizados2MouseClicked

    private void lblCursosPropuestosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosPropuestosMouseClicked
        this.dispose();
        new cursosPropuestos(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosPropuestosMouseClicked

    private void lblCursosPropuestos2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCursosPropuestos2MouseClicked
        this.dispose();
        new cursosPropuestos(this.userDocente,this.instituto).setVisible(true);
    }//GEN-LAST:event_lblCursosPropuestos2MouseClicked

    private void lblCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseEntered
        setUnderline(lblCerrarSesion, true);
    }//GEN-LAST:event_lblCerrarSesionMouseEntered

    private void lblCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseExited
        setUnderline(lblCerrarSesion, false);
    }//GEN-LAST:event_lblCerrarSesionMouseExited

    private void lblCambiarContraseñaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContraseñaMouseClicked
   
        new cambiarContrasenhaUser(userDocente,instituto).setVisible(true);
    }//GEN-LAST:event_lblCambiarContraseñaMouseClicked

    private void lblCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesionMouseClicked
        this.dispose();
        new Inicio(instituto).setVisible(true);
    }//GEN-LAST:event_lblCerrarSesionMouseClicked

    private void lblCambiarContraseñaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContraseñaMouseEntered
        setUnderline(lblCambiarContraseña, true);
    }//GEN-LAST:event_lblCambiarContraseñaMouseEntered

    private void lblCambiarContraseñaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCambiarContraseñaMouseExited
        setUnderline(lblCambiarContraseña, false);
    }//GEN-LAST:event_lblCambiarContraseñaMouseExited



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCambiarContraseña;
    private javax.swing.JLabel lblCantidadCursosCerrado;
    private javax.swing.JLabel lblCantidadCursosFinalizados;
    private javax.swing.JLabel lblCerrarSesion;
    private javax.swing.JLabel lblCursosActivos;
    private javax.swing.JLabel lblCursosActivos2;
    private javax.swing.JLabel lblCursosFinalizados;
    private javax.swing.JLabel lblCursosFinalizados2;
    private javax.swing.JLabel lblCursosPropuestos;
    private javax.swing.JLabel lblCursosPropuestos2;
    private javax.swing.JLabel lblProponerCurso;
    private javax.swing.JLabel lblProponerCurso2;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables

 private static void setUnderline(JLabel label, boolean underline) {
        Font font = label.getFont();
        Map<TextAttribute, Object> attributes = new HashMap<>(font.getAttributes());
        attributes.put(TextAttribute.UNDERLINE, underline ? TextAttribute.UNDERLINE_ON : null);
        label.setFont(font.deriveFont(attributes));
    }
 
  public ArrayList<Curso> obtenerCursosPorEstado(String estado)
  {
      ArrayList<Curso> cursosTotales = instituto.getCursos();
      ArrayList<Curso> cursosCerradosDelDocente = new ArrayList<Curso>();
      
      for(Curso curso : cursosTotales)
      {
          if(curso.getDocente() == this.userDocente && curso.getEstado().equals(estado))
          {
              cursosCerradosDelDocente.add(curso);
          }
      }
      
      return cursosCerradosDelDocente;
  }
  
  public void setLabelCursosCerrados()
  {
      int cantidadCursosCerrados = (obtenerCursosPorEstado("cerrado").size()+obtenerCursosPorEstado("habilitado").size()); // Tu número entero
        String cantCursosCerrados = Integer.toString(cantidadCursosCerrados);
        lblCantidadCursosCerrado.setText(cantCursosCerrados);
  }
  
  public void setLabelCursosFinalizados()
  {
      int cantidadCursosFinalizados = obtenerCursosPorEstado("finalizado").size();
      String cantCursosFinalizados = Integer.toString(cantidadCursosFinalizados);
      lblCantidadCursosFinalizados.setText(cantCursosFinalizados);
  }
  
  public void setLabelSanciones()
  {
////      int cantidadSanciones = userDocente.getSanciones().size();
//      String cantSanciones = Integer.toString(cantidadSanciones);
//      lblCantidadSanciones.setText(cantSanciones);
  }
  
  public void serializarInstituto()
    {
        try {
            FileOutputStream archivoSalida = new FileOutputStream("instituto_serializados.dat");
            ObjectOutputStream objetoSalida = new ObjectOutputStream(archivoSalida);
            objetoSalida.writeObject(instituto);
            objetoSalida.close();
            archivoSalida.close();
        }
        catch (IOException e) {
            e.printStackTrace();
        }
    }

}
